#!/usr/bin/env node
/**
 * compile-tokens.js
 *
 * Reads 00_DESIGN_SYSTEM/tokens.yaml, validates against tokens.schema.json,
 * generates per-format outputs in 00_DESIGN_SYSTEM/compiled/:
 *
 *   tokens.tex   - LaTeX preamble (consumed by render-pdf, render-latex)
 *   tokens.css   - CSS custom properties (consumed by HTML preview)
 *   tokens.json  - Structured form (consumed by render scripts)
 *
 * No external processes are spawned by this script. It only reads YAML/JSON
 * and writes generated text files.
 */

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');
const Ajv = require('ajv');
const addFormats = require('ajv-formats');

const REPO_ROOT = path.resolve(__dirname, '..');
const TOKENS_PATH = path.join(REPO_ROOT, '00_DESIGN_SYSTEM', 'tokens.yaml');
const SCHEMA_PATH = path.join(REPO_ROOT, '00_DESIGN_SYSTEM', 'schemas', 'tokens.schema.json');
const OUT_DIR = path.join(REPO_ROOT, '00_DESIGN_SYSTEM', 'compiled');

function fail(msg) {
  console.error(`compile-tokens: ${msg}`);
  process.exit(1);
}

function hexToRgb(hex) {
  const m = /^#([0-9a-f]{6})$/i.exec(hex);
  if (!m) return '0,0,0';
  const n = parseInt(m[1], 16);
  return `${(n >> 16) & 255},${(n >> 8) & 255},${n & 255}`;
}

function buildLatexPreamble(tokens) {
  const lines = [];
  lines.push('% Generated by scripts/compile-tokens.js - do not edit by hand.');
  lines.push(`% Source: 00_DESIGN_SYSTEM/tokens.yaml (version ${tokens.version})`);
  lines.push('');
  lines.push('% Fonts (requires LuaLaTeX with fontspec)');
  lines.push('\\usepackage{fontspec}');
  lines.push(`\\setmainfont{${tokens.typography.body_font}}`);
  lines.push(`\\setsansfont{${tokens.typography.heading_font}}`);
  lines.push(`\\setmonofont{${tokens.typography.code_font}}`);
  lines.push('');
  lines.push('% Type metrics');
  lines.push(`\\renewcommand{\\baselinestretch}{${tokens.typography.line_height}}`);
  lines.push('');
  lines.push('% Colors');
  // xcolor is loaded by Pandoc's default LaTeX template; pass our options via
  // PassOptionsToPackage to avoid an option clash when Pandoc loads it without
  // options before tokens.tex is injected via --include-in-header.
  lines.push('\\PassOptionsToPackage{table,RGB}{xcolor}');
  lines.push(`\\definecolor{textcolor}{RGB}{${hexToRgb(tokens.colors.text)}}`);
  lines.push(`\\definecolor{accentcolor}{RGB}{${hexToRgb(tokens.colors.accent)}}`);
  lines.push(`\\definecolor{linkcolor}{RGB}{${hexToRgb(tokens.colors.link)}}`);
  if (tokens.colors.code_background) {
    lines.push(`\\definecolor{codebgcolor}{RGB}{${hexToRgb(tokens.colors.code_background)}}`);
  }
  lines.push('');
  lines.push('% Page geometry');
  lines.push('\\usepackage{geometry}');
  const margin = (tokens.spacing && tokens.spacing.page_margin) || '1in';
  lines.push(`\\geometry{margin=${margin}}`);
  lines.push('');
  lines.push('% Hyperlink styling');
  lines.push('\\usepackage{hyperref}');
  lines.push('\\hypersetup{colorlinks=true,linkcolor=linkcolor,urlcolor=linkcolor,citecolor=accentcolor}');

  // Editorial layer — sits on top of the base preamble. See the editorial
  // group in tokens.yaml. Translates the design decisions from
  // 00_DESIGN_SYSTEM/editorial/editorial.css into LaTeX equivalents:
  // light paper surface, Source Serif body, Space Grotesk display headings,
  // restrained accent colors, drop-cap / pull-quote / eyebrow / sidenote
  // helpers ready for use in body markdown via raw-LaTeX or class spans.
  if (tokens.editorial && tokens.editorial.enabled !== false) {
    const ed = tokens.editorial;
    lines.push('');
    lines.push('% =====================================================');
    lines.push('% Editorial layer (longform reading register)');
    lines.push('% =====================================================');

    // Page surface + ink override — applied AFTER base color setup so the
    // editorial palette wins.
    if (ed.surface && ed.surface.paper) {
      lines.push(`\\definecolor{paper}{RGB}{${hexToRgb(ed.surface.paper)}}`);
      lines.push('\\pagecolor{paper}');
    }
    if (ed.ink && ed.ink.primary) {
      lines.push(`\\definecolor{ink}{RGB}{${hexToRgb(ed.ink.primary)}}`);
      lines.push('\\color{ink}');
    }

    // Editorial link colors override the base hyperref setup.
    if (ed.link && ed.link.default) {
      lines.push(`\\definecolor{edlink}{RGB}{${hexToRgb(ed.link.default)}}`);
      lines.push('\\hypersetup{linkcolor=edlink,urlcolor=edlink,citecolor=edlink}');
    }
    if (ed.link && ed.link.hover) {
      lines.push(`\\definecolor{dropcap}{RGB}{${hexToRgb(ed.link.hover)}}`);
    }

    // Editorial main font — overrides body_font from the base layer.
    if (ed.typography && ed.typography.serif_body) {
      lines.push(`\\setmainfont{${ed.typography.serif_body}}[Ligatures=TeX,Numbers=OldStyle]`);
    }
    // Display font for headings — Space Grotesk is the 626 Labs brand display
    // face; hardcoded here because the editorial layer IS the 626 Labs editorial
    // register. Override via tokens.yaml typography.heading_font on the base
    // layer if you fork outside the brand.
    lines.push('\\setsansfont{Space Grotesk}[Ligatures=TeX]');
    lines.push('\\usepackage{sectsty}');
    lines.push('\\allsectionsfont{\\sffamily\\mdseries}');

    // Body line-height (clamped to LaTeX-reasonable range).
    if (ed.typography && ed.typography.line_height_body) {
      lines.push(`\\linespread{${ed.typography.line_height_body}}`);
    }

    // Drop cap — \lettrine{F}{irst paragraph} at the start of an opening graf.
    // Color picked from editorial.link.hover (the magenta-dim accent).
    lines.push('\\usepackage{lettrine}');
    if (ed.link && ed.link.hover) {
      lines.push('\\renewcommand{\\LettrineFontHook}{\\color{dropcap}\\sffamily}');
    }

    // Pull quote — italic, indented, vertical breathing room.
    lines.push('\\usepackage{quoting}');
    lines.push('\\quotingsetup{font=itshape,leftmargin=2em,rightmargin=2em,vskip=0.8em}');
    lines.push('\\newenvironment{pullquote}{\\begin{quoting}}{\\end{quoting}}');

    // Eyebrow — small uppercase label above a title or section head.
    // Use as: \eyebrow{Field Notes · No. 014 · Build log}
    lines.push('\\newcommand{\\eyebrow}[1]{{\\sffamily\\fontsize{10pt}{13pt}\\selectfont\\textcolor{edlink}{\\MakeUppercase{#1}}\\par\\vspace{0.4em}}}');

    // Sidenote — margin annotation. Pandoc body markdown can reach this via
    // raw LaTeX: `\sidenote{...}` or via custom Lua filter.
    lines.push('\\newcommand{\\sidenote}[1]{\\marginpar{\\small\\sffamily\\textcolor{ink}{#1}}}');
  }

  return lines.join('\n') + '\n';
}

function buildCss(tokens) {
  const lines = [];
  lines.push('/* Generated by scripts/compile-tokens.js - do not edit by hand. */');
  lines.push(`/* Source: 00_DESIGN_SYSTEM/tokens.yaml (version ${tokens.version}) */`);
  lines.push(':root {');
  lines.push(`  --font-body: "${tokens.typography.body_font}", serif;`);
  lines.push(`  --font-heading: "${tokens.typography.heading_font}", sans-serif;`);
  lines.push(`  --font-code: "${tokens.typography.code_font}", monospace;`);
  lines.push(`  --font-size-base: ${tokens.typography.base_size};`);
  lines.push(`  --line-height-base: ${tokens.typography.line_height};`);
  lines.push(`  --color-text: ${tokens.colors.text};`);
  lines.push(`  --color-background: ${tokens.colors.background};`);
  lines.push(`  --color-accent: ${tokens.colors.accent};`);
  lines.push(`  --color-link: ${tokens.colors.link};`);
  if (tokens.colors.code_background) {
    lines.push(`  --color-code-bg: ${tokens.colors.code_background};`);
  }
  lines.push('}');

  // Editorial layer — sits on top of base tokens. See 00_DESIGN_SYSTEM/editorial/editorial.css
  // for the full component classes; these are the variables that feed both that file
  // and any HTML render template.
  if (tokens.editorial && tokens.editorial.enabled !== false) {
    const ed = tokens.editorial;
    lines.push('');
    lines.push('/* Editorial layer (longform register) */');
    lines.push(':root {');
    if (ed.surface) {
      if (ed.surface.paper)      lines.push(`  --ed-paper: ${ed.surface.paper};`);
      if (ed.surface.paper_soft) lines.push(`  --ed-paper-soft: ${ed.surface.paper_soft};`);
      if (ed.surface.paper_deep) lines.push(`  --ed-paper-deep: ${ed.surface.paper_deep};`);
    }
    if (ed.ink) {
      if (ed.ink.primary)   lines.push(`  --ed-ink: ${ed.ink.primary};`);
      if (ed.ink.secondary) lines.push(`  --ed-ink-2: ${ed.ink.secondary};`);
      if (ed.ink.tertiary)  lines.push(`  --ed-ink-3: ${ed.ink.tertiary};`);
      if (ed.ink.muted)     lines.push(`  --ed-ink-muted: ${ed.ink.muted};`);
    }
    if (ed.link) {
      if (ed.link.default) lines.push(`  --ed-link: ${ed.link.default};`);
      if (ed.link.hover)   lines.push(`  --ed-link-hover: ${ed.link.hover};`);
    }
    if (ed.typography) {
      if (ed.typography.serif_body)        lines.push(`  --font-serif: "${ed.typography.serif_body}", "Iowan Old Style", "Georgia", serif;`);
      if (ed.typography.measure)           lines.push(`  --ed-measure: ${ed.typography.measure};`);
      if (ed.typography.page_max)          lines.push(`  --ed-page-max: ${ed.typography.page_max};`);
      if (ed.typography.line_height_body)  lines.push(`  --ed-lh-body: ${ed.typography.line_height_body};`);
      if (ed.typography.line_height_pull)  lines.push(`  --ed-lh-pull: ${ed.typography.line_height_pull};`);
    }
    if (ed.scale) {
      const s = ed.scale;
      if (s.h1)       lines.push(`  --ed-t-h1: ${s.h1};`);
      if (s.h2)       lines.push(`  --ed-t-h2: ${s.h2};`);
      if (s.h3)       lines.push(`  --ed-t-h3: ${s.h3};`);
      if (s.dek)      lines.push(`  --ed-t-dek: ${s.dek};`);
      if (s.body)     lines.push(`  --ed-t-body: ${s.body};`);
      if (s.pull)     lines.push(`  --ed-t-pull: ${s.pull};`);
      if (s.caption)  lines.push(`  --ed-t-caption: ${s.caption};`);
      if (s.eyebrow)  lines.push(`  --ed-t-eyebrow: ${s.eyebrow};`);
      if (s.footnote) lines.push(`  --ed-t-foot: ${s.footnote};`);
    }
    lines.push('}');
  }
  return lines.join('\n') + '\n';
}

function main() {
  if (!fs.existsSync(TOKENS_PATH)) fail(`tokens.yaml not found at ${TOKENS_PATH}`);
  if (!fs.existsSync(SCHEMA_PATH)) fail(`tokens.schema.json not found at ${SCHEMA_PATH}`);

  let tokens;
  try {
    tokens = yaml.load(fs.readFileSync(TOKENS_PATH, 'utf8'));
  } catch (e) {
    fail(`tokens.yaml parse error: ${e.message}`);
  }

  const ajv = new Ajv({ allErrors: true, strict: false });
  addFormats(ajv);
  const schema = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf8'));
  const validate = ajv.compile(schema);
  if (!validate(tokens)) {
    console.error('tokens.yaml failed schema validation:');
    for (const err of validate.errors) {
      console.error(`  ${err.instancePath || '/'}: ${err.message}`);
    }
    process.exit(1);
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(path.join(OUT_DIR, 'tokens.tex'), buildLatexPreamble(tokens));
  fs.writeFileSync(path.join(OUT_DIR, 'tokens.css'), buildCss(tokens));
  fs.writeFileSync(path.join(OUT_DIR, 'tokens.json'), JSON.stringify(tokens, null, 2));

  console.log(`compile-tokens: wrote ${OUT_DIR}/{tokens.tex, tokens.css, tokens.json}`);
  console.log(`  version: ${tokens.version}`);
}

main();
